### ISSUE TITLE
questions about output 

### ISSUE THREAD

**Issue by gpp8p** [natanielruiz/dockerface#2] opened 2017-10-25 17:34 UTC
Why is the output video upside-down, and what are the columns contained in the video-det-fold-xxxx.txtx file ?

**Comment by natanielruiz** [comment] 2017-10-25 19:36
Hello gpp8p,
I have not encountered this bug before; I don't see how this can happen - can you send me an example of the video you are running and the output, this would help me diagnose the issue.

The columns contained in video-det-fold-xxx.txt are:
frame_number x_min     y_min     x_max     y_max     confidence_score

Where (x_min,y_min) denote the coordinates of the upper-left corner of the bounding box in image intrinsic coordinates (ref. https://www.mathworks.com/help/images/image-coordinate-systems.html) and (x_max, y_max) denote the coordinates of the lower-right corner of the bounding box in image intrinsic coordinates.

confidence_score denotes the probability output of the model that the detection is correct (it is a number contained in the closed interval [0,1])

**Comment by natanielruiz** [comment] 2017-10-25 19:56
Also can you please try to process a different video (for example a video from YouTube) and tell me if the problem is still there? Thank you :)

**Comment by natanielruiz** [comment] 2017-11-01 22:59
Alright I'm closing this due to lack of response. If you still have this bug please reopen.

**Closed as completed by natanielruiz** 2017-11-01 22:59 UTC
